spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/karnan131k/CloudConfiguration
          search-paths:
          - '{application}'
        default-label: main

server:
  port: 8081






#server:
#  port: 8191
#spring:#  cloud:#    config:#      server:#        git:#          uri: https://github.com/karnan131k/spring-cloud-config-store
#          default-label: master
#          search-paths:#          - '*service'

# we can call values in different ways
# http://localhost:8191/membership-dev.json
# http://localhost:8191/membership-dev.yml
# http://localhost:8191/membership-dev.properties
# http://localhost:8191/membership/3e849d4d4d08338c1c74c9f6fc40b3b30e641242 (previous commit id)
# http://localhost:8191/membership/dev
# http://localhost:8191/membership/prod
# http://localhost:8191/membership/default