server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
spring:  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
    url: jdbc:mysql://localhost:3306/sample
#it will taking name as what ever name mention in model class attibutes as a colunm name in data base  jpa:    hibernate:      naming:        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
