spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/karnan131k/CloudConfiguration
          search-paths:
          - '{application}'
        default-label: main

server:
  port: 8191